### PR TITLE
Enhanced VPC API to support IPv6 and to either auto assign a subnet f…

### PR DESCRIPTION
**Pull request by sureshr-hasvik**
…rom Zone superIPv6 CIDR or validate user provided IPv6 CIDR

### CODE REVIEW

**Comment by sureshr-hasvik** [comment]
I agree, it will could be too much but when looking at the IPv6 networks when it is split we could have around 16K networks(depending on the prefix length). 10 could be little too. I would suggest we could at least have 100. Any way, it is configurable also. let me know, I will make the changes..

**Comment by remibergsma** [comment]
@wilderrodrigues @sureshr-hasvik Doing a query to the data base each time you try a CIDR doesn't feel to me as the best solution. Why not query the CIDRs that are already in use (instead of only the count) and do a compare with that in Java? Will be much faster and the data base has less load.

**Comment by sureshr-hasvik** [comment]
Hhhhmmm. In that case 
a) we would be looping with 16k entries(worst case) in Java  where as in current design worst case is 100 or some configured value
b) another issue I see is the state of the CIDR. Because we get all the entries at one shot and loop thru, by the time we find an CIDR it could very well be used by other thread. So, we might not know the latest state of the CIDR that we try to set to VPC. 

Thanks for comments and suggessions. Appreciate it. These suggessions also popped up when I was working on this. But, when I looked at the current implementation of IPv6 ip allocation, it also used similar logic. So, I felt it makes sense.

**Comment by remibergsma** [comment]
a) If you have that many VPCs with CIDRs your random approach with all its SQL queries is definitely not going to be more efficient nor faster I'd say ;-)
b) good point, you can double check it before using. Takes one extra query.

**Comment by sureshr-hasvik** [comment]
Are you suggesting to not use random at all. Rather, get the next available CIDR. Because, by using random, we try get probable CIDR that is not used.

But no problem, I can change the implementation as per your suggestion. Let me know if you want to or not want to use random :)

**Comment by sureshr-hasvik** [comment]
Well, I think we can not get rid of random CIDR generation because we need to find an CIDR that is not used. So, we need to either iterate thru the entire list and find the one that is not used or sort the list and find one. Still again there needs to be retry here too, if the item we found after we using above logic is already used by second check..

May be we can discuss on monday, it will be better :)

**Comment by wilderrodrigues** [comment]
@remibergsma and @sureshr-hasvik 

Is better to comment on the sourcecode line, so we have a reference. I just added comments concerning the retry and validation methods.

Cheers,
Wilder

**Comment by sureshr-hasvik** [comment]
Hi @wilderrodrigues 

NetworkIPv6SearchRetryMax was not added by me. It is part of the old code that supports IPV6 in Shared network. Changing this is little tricky because, this deals with IPv6 address which is in order of 2^64. I remember that while discussing about this in the conf call with @snuf, he mentioned that for IP addresses random should be fine. Please discuss with him if needed. We need a another epic If this also needs to be fixed as this will change the current support for IPv6 in shared network. I removed only the retry that I added specific for VPC as discussed in the conf call.

Yes, this list is sorted. But, the point here is find that IP which needs to be generated. There are multiple ways to come up with that one IP. Initial approach was picking one some random IP. But, then due some performance issues, we changed the logic to find that first unused IP by looking at the list. 

True, binary search could be done. But, to do a binary search we need to find that one IP and only then we can do a binary search. But, the point here is to find that one unused IP.

**Comment by wilderrodrigues** [comment]
Hi Suresh,

Let me see if I understood it correctly. You are saying that the method  assignDirectIp6Address() already existed, right? In your first PR, that method has the following snippet of code:

image

And the new method - getUniqueVpcIp6Cidr() - had the following snippet of code:

image


Also, in the first PR the Config.java class had the following Enums:

image

So, you did not add the NetworkIPv6SearchRetryMax enum, fine. However, you just copied the same bad behaviour.

My point is: the logic was the same… it was bad, and it was the same.

In software engineer when we see something like that we fix it, we do not copy it. At least, that’s how I learned.

Concerning the Binary Search, it was just a remark… no need to change it now. But if I may add one small thing…

- One uses a search algorithm to find something, that’s crystal clear. In the case of the IPv6 stuff, we want to make sure that the CIDR is not used by existing VPCs, thus it won’t be found in the list, right? If one thinks out of the box, the binary search will say that the CIDR was not found, right? Isn’t that what the for-loop is doing?

Cheers,
Wilder

**Comment by remibergsma** [comment]
Source repo deleted, closing PR.

**Pull request closed without merging**
